import React, { useState } from "react";
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";

export default function Login() {
  const [, setLocation] = useLocation(); const utils = trpc.useUtils(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const next = new URLSearchParams(window.location.search).get("next") || "/dashboard";
  const login = trpc.auth.login.useMutation({ onSuccess: user => { utils.auth.me.setData(undefined, user); setLocation(next.startsWith("/") ? next : "/dashboard"); }, onError: value => setError(value.message) });
  return <main className="landing-grid grid min-h-screen place-items-center bg-[#f7faff] p-5"><section className="w-full max-w-md rounded-[1.75rem] border border-[#dbe6f1] bg-white p-7 surface-shadow sm:p-9"><Link href="/" className="text-sm font-extrabold text-[#18446e]">Job Sarthi</Link><p className="mt-9 eyebrow text-[#277b6a]">Independent account</p><h1 className="mt-3 font-display text-4xl font-semibold tracking-[-.06em] text-[#112b51]">Welcome back.</h1><p className="mt-3 text-sm leading-6 text-[#66778b]">Sign in with your Job Sarthi email and password.</p><form className="mt-7 space-y-5" onSubmit={event => { event.preventDefault(); setError(""); login.mutate({ email, password }); }}><div className="space-y-2"><Label htmlFor="login-email">Email</Label><Input id="login-email" type="email" autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} required /></div><div className="space-y-2"><div className="flex items-center justify-between"><Label htmlFor="login-password">Password</Label><Link href="/forgot-password" className="text-xs font-bold text-[#216b89]">Forgot password?</Link></div><Input id="login-password" type="password" autoComplete="current-password" value={password} onChange={event => setPassword(event.target.value)} required /></div>{error && <div role="alert" className="rounded-xl bg-[#fff3f1] p-3 text-sm font-medium text-[#9e4e48]"><p>{error}</p>{error.includes("password setup") && <Link href="/forgot-password" className="mt-2 inline-block font-bold underline underline-offset-2">Request a password setup link</Link>}</div>}<Button className="h-11 w-full rounded-xl bg-[#0d2c58] font-bold hover:bg-[#12386d]" disabled={login.isPending}>{login.isPending ? "Signing in…" : "Sign in"}</Button></form><div className="my-7 flex items-center gap-3 text-xs text-[#8a99a9]"><span className="h-px flex-1 bg-[#e0e8f0]" />OR<span className="h-px flex-1 bg-[#e0e8f0]" /></div><Button type="button" variant="outline" className="h-11 w-full rounded-xl" disabled title="Google sign-in is not configured">Google sign-in unavailable</Button><p className="mt-7 text-center text-sm text-[#66778b]">Don&apos;t have an account? <Link href="/register" className="font-bold text-[#216b89]">Create one</Link></p></section></main>;
}
