import React, { useState } from "react";
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";

export default function Register() {
  const [, setLocation] = useLocation(); const utils = trpc.useUtils(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [acceptedTerms, setAcceptedTerms] = useState(false); const [error, setError] = useState("");
  const register = trpc.auth.register.useMutation({ onSuccess: user => { utils.auth.me.setData(undefined, user); setLocation("/onboarding"); }, onError: value => setError(value.message) });
  return <main className="landing-grid grid min-h-screen place-items-center bg-[#f7faff] p-5"><section className="w-full max-w-md rounded-[1.75rem] border border-[#dbe6f1] bg-white p-7 surface-shadow sm:p-9"><Link href="/" className="text-sm font-extrabold text-[#18446e]">Job Sarthi</Link><p className="mt-9 eyebrow text-[#277b6a]">Independent account</p><h1 className="mt-3 font-display text-4xl font-semibold tracking-[-.06em] text-[#112b51]">Create your account.</h1><p className="mt-3 text-sm leading-6 text-[#66778b]">Your profile, applications, and preferences stay linked to your Job Sarthi account.</p><form className="mt-7 space-y-4" onSubmit={event => { event.preventDefault(); setError(""); if (!acceptedTerms) return setError("Please accept the Terms and Privacy Policy."); register.mutate({ name, email, password, confirmPassword, acceptedTerms: true }); }}><div className="space-y-2"><Label htmlFor="register-name">Name</Label><Input id="register-name" autoComplete="name" value={name} onChange={event => setName(event.target.value)} required /></div><div className="space-y-2"><Label htmlFor="register-email">Email</Label><Input id="register-email" type="email" autoComplete="email" value={email} onChange={event => setEmail(event.target.value)} required /></div><div className="space-y-2"><Label htmlFor="register-password">Password</Label><Input id="register-password" type="password" autoComplete="new-password" value={password} onChange={event => setPassword(event.target.value)} required /><p className="text-xs text-[#718196]">At least 10 characters. Avoid common passwords.</p></div><div className="space-y-2"><Label htmlFor="register-confirm">Confirm password</Label><Input id="register-confirm" type="password" autoComplete="new-password" value={confirmPassword} onChange={event => setConfirmPassword(event.target.value)} required /></div><label className="flex cursor-pointer items-start gap-3 text-sm leading-5 text-[#617388]"><input type="checkbox" className="mt-1" checked={acceptedTerms} onChange={event => setAcceptedTerms(event.target.checked)} />I agree to the Terms and Privacy Policy.</label>{error && <p role="alert" className="rounded-xl bg-[#fff3f1] p-3 text-sm font-medium text-[#9e4e48]">{error}</p>}<Button className="h-11 w-full rounded-xl bg-[#0d2c58] font-bold hover:bg-[#12386d]" disabled={register.isPending}>{register.isPending ? "Creating account…" : "Create account"}</Button></form><div className="my-7 flex items-center gap-3 text-xs text-[#8a99a9]"><span className="h-px flex-1 bg-[#e0e8f0]" />OR<span className="h-px flex-1 bg-[#e0e8f0]" /></div><Button type="button" variant="outline" className="h-11 w-full rounded-xl" disabled title="Google sign-in is not configured">Google sign-in unavailable</Button><p className="mt-7 text-center text-sm text-[#66778b]">Already have an account? <Link href="/login" className="font-bold text-[#216b89]">Sign in</Link></p></section></main>;
}
