import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { trpc } from "@/lib/trpc";
import { Bell, Check, X } from "lucide-react";
import { useLocation } from "wouter";

export function NotificationMenu() {
  const [, setLocation] = useLocation(); const inbox = trpc.notifications.list.useQuery(); const utils = trpc.useUtils();
  const markRead = trpc.notifications.markRead.useMutation({ onSuccess: () => utils.notifications.list.invalidate() });
  const dismiss = trpc.notifications.dismiss.useMutation({ onSuccess: () => utils.notifications.list.invalidate() });
  const unread = inbox.data?.unreadCount ?? 0;
  const open = (notification: NonNullable<typeof inbox.data>["items"][number]) => { if (!notification.readAt) markRead.mutate({ notificationId: notification.id }); if (notification.href) setLocation(notification.href); };
  return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="relative ml-auto rounded-xl text-[#57748f]" aria-label={unread ? `${unread} unread notifications` : "Notifications"}><Bell className="h-4.5 w-4.5" />{unread > 0 && <span className="absolute -right-0.5 -top-0.5 grid min-w-4 place-items-center rounded-full bg-[#d76354] px-1 text-[10px] font-extrabold leading-4 text-white">{unread > 9 ? "9+" : unread}</span>}</Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-[min(25rem,calc(100vw-2rem))] rounded-2xl border-[#dce6ef] p-0"><div className="border-b border-[#edf1f5] px-4 py-3"><p className="font-extrabold text-[#244360]">Notifications</p><p className="mt-0.5 text-xs text-[#7a8c9d]">Meaningful updates from your private workspace.</p></div><div className="max-h-96 overflow-y-auto p-2">{inbox.isLoading ? <div className="p-5 text-sm text-[#74869a]">Loading notifications…</div> : inbox.data?.items.length ? inbox.data.items.map(notification => <div className={`group flex gap-2 rounded-xl p-3 transition-colors hover:bg-[#f6f9fb] ${notification.readAt ? "" : "bg-[#f2f8f6]"}`} key={notification.id}><button className="min-w-0 flex-1 text-left" onClick={() => open(notification)}><p className="text-sm font-extrabold text-[#294864]">{notification.title}</p><p className="mt-1 text-xs leading-5 text-[#6c8095]">{notification.body}</p><p className="mt-1.5 text-[11px] text-[#8797a7]">{new Date(notification.createdAt).toLocaleDateString()}</p></button><div className="flex shrink-0 flex-col gap-1"><button aria-label="Mark as read" className="grid h-7 w-7 place-items-center rounded-lg text-[#6d859d] hover:bg-[#e8f0f6]" disabled={Boolean(notification.readAt) || markRead.isPending} onClick={() => markRead.mutate({ notificationId: notification.id })}><Check className="h-3.5 w-3.5" /></button><button aria-label="Dismiss notification" className="grid h-7 w-7 place-items-center rounded-lg text-[#8292a0] hover:bg-[#f8ecea] hover:text-[#ad554b]" disabled={dismiss.isPending} onClick={() => dismiss.mutate({ notificationId: notification.id })}><X className="h-3.5 w-3.5" /></button></div></div>) : <div className="p-6 text-center"><Bell className="mx-auto h-5 w-5 text-[#89a0b4]" /><p className="mt-3 text-sm font-bold text-[#536f89]">No notifications yet.</p><p className="mt-1 text-xs leading-5 text-[#8493a2]">Important profile, resume, application, and high-match updates will appear here.</p></div>}</div></DropdownMenuContent></DropdownMenu>;
}
